# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62bef74f750dec09a258fee36aff9f7c62ef91c8bd4f820a5da73479bc072a50720484870b64a30a655d044353681e5ddfe84bc40dba5322fb010c163c51af7

test:
  secret_key_base: 4c4d8e2baf22d4e4b90c595324aec4c93700c02bafb4c65dd838795b30d406598e87ab1352e5088efb00f61df0b00fd20b849503ebb080907e3dca44489a9632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
